name: CI/CD

on:
  workflow_dispatch:
  push:
      tags:
        - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: install package deps
        run: npm ci

      - name: build package
        run: npm run build

      - name: run tests
        run: npm run tests

      - name: run app
        run: npm run start
