name: CI/CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install small-ci
        run: npm i small-ci

      - name: run tracker script
        run: npx small-ci tracker --debug
        shell: bash
        env:
          SCI_RELEASE_OAUTH: ${{ secrets.SCI_TRACKER_OAUTH }}
