name: CI/CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install small-ci
        run: npm i small-ci

      - name: install deps
        run: npm ci

      - name: create issue on tracker with changelogs
        run: npx small-ci tracker --debug
        shell: bash
        env:
          SCI_TRACKER_OAUTH: ${{ secrets.SCI_TRACKER_OAUTH }}

      - name: run tests
        run: npm run test &> test.log

      - name: add tests results to tracker
        run: npx small-ci tracker --debug --comment="$(<test.log)"
        shell: bash
        env:
          SCI_TRACKER_OAUTH: ${{ secrets.SCI_TRACKER_OAUTH }}

      - name: build docker image
        run: npx small-ci docker &> docker.log

      - name: add docker results to tracker
        run: npx small-ci tracker --comment="$(<docker.log)"
        shell: bash
        env:
          SCI_TRACKER_OAUTH: ${{ secrets.SCI_TRACKER_OAUTH }}